### ISSUE TITLE
twrp 3.6.2 (3.7.skkk) can not decrypt data

### ISSUE THREAD

**Issue by cyberboh** [sekaiacg/device_xiaomi_alioth-TWRP#1]
I'm using this recovery:
`https://dl.akr-developers.com/?file=skkk/TWRP/A12/v3.7_A12/3.6.2_12-RedmiK40-RedmiPOCOF3_v3.7_A12-alioth-skkk_f077017d.img`
ROM is voidUI: 
`https://github.com/VoidUI`
`https://github.com/VoidUI-Devices/device_xiaomi_alioth`

When entering TWRP it does not ask for decrypt password, but while trying to decrypt it failed
Log attached:
[logcat.log](https://github.com/sekaiacg/device_xiaomi_alioth-TWRP/files/8988073/logcat.log)

**Comment by sekaiacg** [comment]
> 

No recovery.log included, no information available.  You can try switching the password type in the rom.

**Comment by cyberboh** [comment]
> > 
> 
> No recovery.log included, no information available. You can try switching the password type in the rom.

sorry, here's the log
on previous twrp i can decrypt it easily with same password type
[recovery.log](https://github.com/sekaiacg/device_xiaomi_alioth-TWRP/files/8988977/recovery.log)

**Comment by sekaiacg** [comment]
> 

`Failed to read "/data/system_de/0/spblob/9c54c24fd903cd0.pwd"
`
Please enter the /data/system_de/0/spblob/ directory to view the file list.  Let me know the list.

Some people also reported that they could not decrypt, and they found that it was normal after switching the password type.  At the same time, you can switch the password type back to the original one.  So I don't know the specific problem.

**Comment by cyberboh** [comment]
> 9c54c24fd903cd0

Attached the list files
[spblob.zip](https://github.com/sekaiacg/device_xiaomi_alioth-TWRP/files/8992615/spblob.zip)

I switched to pattern from PIN type, it worked. Maybe spblob is the encrypted password or something

**Comment by sekaiacg** [comment]
> > 9c54c24fd903cd0
> 
> Attached the list files [spblob.zip](https://github.com/sekaiacg/device_xiaomi_alioth-TWRP/files/8992615/spblob.zip)
> 
> I switched to pattern from PIN type, it worked. Maybe spblob is the encrypted password or something

The file is not abnormal, it may have been extracted after the switch, can't confirm what happened...
