### ISSUE TITLE
Add `vendor_boot-as-recovery` supported rom

### ISSUE THREAD

**Issue by cyberboh** [sekaiacg/device_xiaomi_alioth-TWRP#3]
skkk twrp can not start on the rom if you installed it as permanently that has `vendor_boot-as-recovery` like lineage, voidui, pixel experience, etc 
after flashing a rom with ticked "install recovery after installing a rom" it just go black and blank screen then rebooted to system instead of recovery

**Comment by sekaiacg** [comment]
Thanks for your feedback.
The ROM you are using uses the configuration below. 

https://source.android.com/docs/core/architecture/partitions/vendor-boot-partitions?hl=en
```
To build recovery resources as a standalone recovery ramdisk in vendor_boot:

Set BOARD_BOOT_HEADER_VERSION to 4.
Set BOARD_MOVE_RECOVERY_RESOURCES_TO_VENDOR_BOOT to true.
Set BOARD_INCLUDE_RECOVERY_RAMDISK_IN_VENDOR_BOOT to true.
This adds a vendor ramdisk fragment whose ramdisk_name is recovery and ramdisk_type is VENDOR_RAMDISK_TYPE_RECOVERY. The ramdisk then contains all recovery files, which are files installed under $(TARGET_RECOVERY_ROOT_OUT).
```

Under this configuration, cannot start twrp on the ramdisk of the boot partition
Sorry, I have no plans to support it, please use the RECOVERY that comes with the ROM.
